http:
  routers:
    # Traefik Dashboard
    dashboard:
      rule: "(PathPrefix(`${MOVIE_MATE_BASE_PATH}/api`) || PathPrefix(`${MOVIE_MATE_BASE_PATH}/dashboard`))"
      service: api@internal
      entryPoints:
        - internal

  middlewares:
    dapr-rewrite:
      replacePathRegex:
        regex: "^/([^/]+)(/.*)?"
        replacement: "/v1.0/invoke/${1}/method${2}"
        # Example: /mm-user-service/profile → /v1.0/invoke/mm-user-service/method/profile

