http:
  routers:
    # Traefik Dashboard
    dashboard:
      rule: "PathPrefix(`${MOVIE_MATE_BASE_PATH}/traefik`)"
      service: api@internal
      entryPoints:
        - internal
      middlewares:
        - oauth-redirect@file

  middlewares:
    dapr-rewrite:
      replacePathRegex:
        regex: "^/([^/]+)(/.*)?"
        replacement: "/v1.0/invoke/${1}/method${2}"
        # Example: /mm-user-service/profile → /v1.0/invoke/mm-user-service/method/profile
    jwt-forwardauth:
      forwardAuth:
        address: "${MOVIE_MATE_USER_SERVICE_TOKEN_VALIDATION_URL}"
        trustForwardHeader: true
        authResponseHeaders:
          - X-User-Id
          - X-User-Username
          - X-User-Email
          - X-User-Roles
          - Authorization
    oauth-proxy-check:
      forwardAuth:
        # Prefer in-cluster service to avoid edge-proxy quirks. Keep external URL if you want.
        # auth -> 201 success, 401 must be middleware that redirects to login
        address: "${MOVIE_MATE_OAUTH_HOST}${MOVIE_MATE_OAUTH_BASE_PATH}/auth"
        trustForwardHeader: true
        authRequestHeaders:
          - Cookie
          - X-Forwarded-Host
          - X-Forwarded-Proto
          - X-Forwarded-Port
          - X-Forwarded-Uri
          - X-Original-Uri
        authResponseHeaders:
          - X-Auth-Request-Email
          - X-Auth-Request-User
          - Authorization
    oauth-proxy-redirect-error:
      plugin:
        redirectErrors:
          status:
            - "401-403"
          target: "${MOVIE_MATE_OAUTH_HOST}${MOVIE_MATE_OAUTH_BASE_PATH}/sign_in?rd={url}"
          outputStatus: 302
    oauth-redirect:
      chain:
        middlewares:
          - oauth-proxy-redirect-error
          - oauth-proxy-check
  
  #Native solution to error
  #    oauth-errors:
  #      errors:
  #        status:
  #          - "401-403"
  #        service:  oauth2-proxy@file
  #        query: "${MOVIE_MATE_OAUTH_BASE_PATH}/sign_in?rd={url}"

  services:
    oauth2-proxy:
      loadBalancer:
        servers:
          - url: "${MOVIE_MATE_OAUTH_HOST}"
        passHostHeader: true