http:
  routers:
    dashboard:
      rule: "Host(`localhost`)"
      entryPoints:
        - internal
      service: api@internal
      middlewares:
        - dashboard-auth

  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "${MOVIE_MATE_API_GATEWAY_DASHBOARD_USER}"