api:
  dashboard: true
  insecure: false

entryPoints:
  internal:
    address: ":8080"

providers:
  consulCatalog:
    endpoint:
      address: "${MOVIE_MATE_DISCOVERY_SERVER_HOST}:${MOVIE_MATE_DISCOVERY_SERVER_PORT}"
    exposedByDefault: false

  file:
    filename: "/etc/traefik/dynamic.yml"
