api:
  dashboard: true
  insecure: false

entryPoints:
  internal:
    address: ":${MOVIE_MATE_API_GATEWAY_INTERNAL_LISTENING_PORT}"


providers:
  file:
    filename: "/etc/traefik/dynamic.yml"
  consulCatalog:
    endpoint:
      address: "${MOVIE_MATE_DISCOVERY_SERVER_HOST}:${MOVIE_MATE_DISCOVERY_SERVER_PORT}"
    exposedByDefault: false

log:
  level: DEBUG
  format: common

accessLog:
  format: common